[wokwi]
version = 1
firmware = ".pio/build/esp32doit-devkit-v1/firmware.bin"
elf = ".pio/build/esp32doit-devkit-v1/firmware.elf"
license = "JnU9NDIzMjg2OTE1NzA1NDU3NjY1Jm49bnVoYXJvbmF6eiU0MGdtYWlsLmNvbSZlPW51aGFyb25henolNDBnbWFpbC5jb20meD0yMDI1MDQyNgAlzVpfMlWL9JqrQZbcMuH7cYDSRCGCLnwPWo0q_SgcBoxq7CjwBi_P4B02o38trnlHVQC5rTyqf3VApr7EVORBAHwg_P_P6o6p4JJ9uj_S_P2QR_PWmqWF2xY_SpX_PwoHxXWR5Fj8m_PkqNr8So2_SlanCbXYUwTxwnJc6TqRtBk5bj1_P_SO98l6FJo_Ss_SIev5OMZWh0icXE_PRXqGT1Ng7pH8xqt5ybg_SsmyM_SEDq_S3HMD63ZB_S_S7ZGNV_SvF_S5xxfBU_SZmrWxQHX7p4hAGmJyA9GsMw9DCIl1f2aXuJkOBzKk7CFGQ_S_PLw79aRnkPPKOgSocyRCy3lk9CwRol0_PwUEFt0UutLYsKp"
[net.allowlist]
domains = ["api.openweathermap.org"]
