
[wokwi]
version = 1
firmware = '.pio/build/esp32dev/firmware.bin'
elf = '.pio/build/esp32dev/firmware.elf'
license = "JnU9NDIzMjg2OTE1NzA1NDU3NjY1Jm49bnVoYXJvbmF6eiU0MGdtYWlsLmNvbSZlPW51aGFyb25henolNDBnbWFpbC5jb20meD0yMDI1MDcxNgCV1L6mUKvGyezsYMlQZ7IkIRbYYyBg0uHrg_PBEIUdji9bWZEYijCvKkO4ywEvPd4HgxLwnH9V8ShoXf1s22thyjDQGj_Pj4g5hB_SSXdVNS_SXvxfWqCp_P0EQOP5LVvdkOM2obyn5G96Lteq3X1Osue9E5U19VQVqjsduhEx9CbSyi7MS4pRwMJ2AUC2kkyvdhdCctrY3JkbkqjD0N9RDmNiGH6T6D_PyX61TaTUccq66KQ6Kq_PJz3BsLoAxFjC6bJhaFR_ST2dm710tVuQrSi45fE_Prr_Sr2CGRE9D38IcKNnGW92qEqKRhommbp1al3NEw6QLT_SQSvSZdMgXzshx1Uwzmy"